export const TRANSLATIONS = {
	en: {
		welcomeBack: "Welcome back!",
		createAccount: "Create account",
		username: "Username",
		email: "Email",
		password: "Password",
		login: "Log In",
		register: "Let's fly!",
		noAccount: "Don't have an account? Sign Up",
		hasAccount: "Already have an account? Log In",
		errorFields: "Oops! Fill in all fields, please",
		errorNetwork: "Backend is resting, check the server",
		success: "Success!",
		error: "Error",
		startLogin: "Sign In",
		startRegister: "Register",
		back: "← Back",
	},
	os: {
		welcomeBack: "Ӕгас цу!",
		createAccount: "Аккаунт скӕнын",
		username: "Архайагы ном",
		email: "Электронны поштӕ",
		password: "Парол",
		login: "Бацӕуын",
		register: "Атахтыстӕм!",
		noAccount: "Аккаунт нӕй? Скӕнын",
		hasAccount: "Аккаунт ис? Бацӕуын",
		errorFields: "Упс! Схӕддзаг кӕнут алы бынат дӕр",
		errorNetwork: "Бэкенд фӕллад у, сервер сгӕрсут",
		success: "Ӕнтыстджын!",
		error: "Рӕдыд",
		startLogin: "Бацӕуын",
		startRegister: "Регистраци",
		back: "← Фӕстӕмӕ",
	},
};
